# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1

jobs:

  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Run something
          command: |
            echo "Hello"
            bash .circleci/files-changed.sh
